apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 10.10.10.14:5000/demo
  newTag: a50ca243853decc27920049de06024821f6a57da
