apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: 10.10.10.14:5000/demo
  newTag: dbbc75ed9ac20eb97a8527301e08b97c60c7aab0
